### ISSUE TITLE
Need your help with installing/running MOD!

### ISSUE THREAD

**Issue by calebproll** [ash47/FeedAndGrowFishResearch#1]
Hi everyone--just downloaded the MOD for all the fish and all levels.  We downloaded the Assembly-CSharp.dll file and dropped the file in the "Managed" folder.  Then attempted to load the game, but received the dreaded "Runtime error" error message.  I've tried a number of the different versions available in this link but all have same error message.

https://github.com/ash47/FeedAndGrowFishResearch/releases

ANy ideas?

Thanks so much.

**Comment by ash47** [comment]
Hi,

We moved this to a new mod loader, you can download / install it for free
from here:

https://www.patreon.com/posts/feed-and-grow-10-31100424

There is the attachment down the bottom which is free to download

**Comment by calebproll** [comment]
Hi,

I downloaded the mod and unzipped in the folders, but not seeing any of the
additional fish.

I overwrote the Assembly-CSharp.dll file in the managed folder and also
dropped the AzzaFortysixMods folder in the Feed and Grow_Data folder.

Is there something I'm missing?

**Comment by ash47** [comment]
So you see the mod loader in the main menu? Are you using the download from
our Patreon, or from this repo?

**Comment by calebproll** [comment]
I see.  Is this the file?

v2019_10_27.zip <https://www.patreon.com/file?h=31100424&i=4645320>

Or do we need to become a patreon by subscribing to have access?

**Comment by ash47** [comment]
It's completely free, if you're having issues downloading it, we need to
fix it

Can you download the file?

**Comment by calebproll** [comment]
I can.

What I'm experiencing is game loads but kiddo isn't seeing any addl fish.

**Comment by ash47** [comment]
Does the game try to update prior to launching?

When you install the mod loader, it's meant to inject itself into the main
menu, on the right hand side of the screen you should see the AzzaFortysix
logo and it should let you turn mods on and off, do you see anything like
that?

**Comment by calebproll** [comment]
I don't think so.

Can you clarify on what you mean by installing the mod loader?

**Comment by ash47** [comment]
Hi,

We're like 80% done stream lining this entire process and making it super
easy, stay tuned for our new release

**Comment by ash47** [comment]
@calebproll I just spotted this again, sorry for the delay in my response, this is the mod Launcher -- https://azzamods.com/

**Comment by calebproll** [comment]
Thank you!  I just opened, and patched the game.  Anything else I need to
do?  My little guy didn't notice any of the extra goodies.

Thank you!

**Comment by ash47** [comment]
Once the game is patched, you need to download and enable mods from within
the launcher, I think the first wave of mods should be almost about to go
public for free -- there is a 14 day delay between when we publish our mods
for our subscibers and when we publish them to the public.

**Comment by calebproll** [comment]
Got it, thanks!
